import type { ApprovedExpenseItem } from './types';

export const INITIAL_APPROVED_EXPENSES: ApprovedExpenseItem[] = [
  {
    id: '1',
    claimId: 'EXP-2026-890',
    employee: 'Emad Moustafa',
    employeeId: 'EMP-0102',
    department: 'Finance',
    reason: 'Whatsapp Summit Fuel Claims',
    category: 'Transportation & Fuel',
    approvedDate: 'Oct 24, 2026',
    approvalChain: '2/3 Approved',
    amount: 500000,
    currency: 'RP',
    bankName: 'Bank Danamon',
    bankAccountNumber: '00360098129033',
    status: 'Ready for Payment',
    receiptsCount: 2,
    receiptName: 'Fuel_Receipt_Summit.pdf',
    notes: 'Approved by Branch Manager & Division Director.'
  },
  {
    id: '2',
    claimId: 'EXP-2026-885',
    employee: 'Sarah Lim',
    employeeId: 'EMP-0145',
    department: 'Umrah',
    reason: 'Site Dinner Accommodation',
    category: 'Client Dinner & Catering Accommodation',
    approvedDate: 'Oct 24, 2026',
    approvalChain: '2/3 Approved',
    amount: 500000,
    currency: 'RP',
    bankName: 'Bank Central Asia (BCA)',
    bankAccountNumber: '8290192831',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Restaurant_Invoice.pdf',
    notes: 'Dinner accommodation for Umrah group guides.'
  },
  {
    id: '3',
    claimId: 'EXP-2026-881',
    employee: 'John Doe',
    employeeId: 'EMP-0188',
    department: 'IT',
    reason: 'Logistics & Transport',
    category: 'Inter-office Logistics & Courier',
    approvedDate: 'Oct 24, 2026',
    approvalChain: '2/3 Approved',
    amount: 500000,
    currency: 'RP',
    bankName: 'Bank Mandiri',
    bankAccountNumber: '1370019284721',
    status: 'Ready for Payment',
    receiptsCount: 2,
    receiptName: 'Courier_Logistics.pdf',
    notes: 'Server backup hardware dispatch.'
  },
  {
    id: '4',
    claimId: 'EXP-2026-878',
    employee: 'Nasser Al-Otaibi',
    employeeId: 'EMP-0205',
    department: 'Accounting',
    reason: 'Office Supplies & Printing',
    category: 'Stationery & Printing',
    approvedDate: 'Oct 24, 2026',
    approvalChain: '2/3 Approved',
    amount: 500000,
    currency: 'RP',
    bankName: 'Al Rajhi Bank',
    bankAccountNumber: '49201928371920',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Print_Shop_Tax_Invoice.pdf',
    notes: 'Quarterly financial report book printing.'
  },
  {
    id: '5',
    claimId: 'EXP-2026-875',
    employee: 'Tariq Mansour',
    employeeId: 'EMP-0130',
    department: 'Operations',
    reason: 'Madinah Branch Hotel Audit Fuel',
    category: 'Transportation & Fuel',
    approvedDate: 'Oct 23, 2026',
    approvalChain: '2/3 Approved',
    amount: 450000,
    currency: 'RP',
    bankName: 'National Commercial Bank (NCB)',
    bankAccountNumber: '10928374829102',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Fuel_Petrol_Oct23.pdf',
    notes: 'Vehicle inspection travel.'
  },
  {
    id: '6',
    claimId: 'EXP-2026-870',
    employee: 'Hesham Mokhtar',
    employeeId: 'EMP-0010',
    department: 'Management',
    reason: 'Client VIP Delegation Lunch',
    category: 'Client Entertainment',
    approvedDate: 'Oct 22, 2026',
    approvalChain: '2/3 Approved',
    amount: 1000000,
    currency: 'RP',
    bankName: 'Bank Danamon',
    bankAccountNumber: '00360011223344',
    status: 'Ready for Payment',
    receiptsCount: 3,
    receiptName: 'VIP_Lunch_Receipt.pdf',
    notes: 'Annual partnership meeting hosting.'
  },
  {
    id: '7',
    claimId: 'EXP-2026-865',
    employee: 'Fahad Al-Harbi',
    employeeId: 'EMP-0220',
    department: 'Umrah',
    reason: 'Emergency Bus Maintenance Surcharge',
    category: 'Transportation & Fuel',
    approvedDate: 'Oct 21, 2026',
    approvalChain: '2/3 Approved',
    amount: 500546,
    currency: 'RP',
    bankName: 'Riyad Bank',
    bankAccountNumber: '38192039481920',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Bus_Repair_Makkah.pdf',
    notes: 'Pilgrim transfer fleet radiator service.'
  },
  {
    id: '8',
    claimId: 'EXP-2026-860',
    employee: 'Layla Hassan',
    employeeId: 'EMP-0235',
    department: 'HR',
    reason: 'Employee Training Materials & Printing',
    category: 'Stationery & Printing',
    approvedDate: 'Oct 20, 2026',
    approvalChain: '2/3 Approved',
    amount: 350000,
    currency: 'RP',
    bankName: 'Bank Danamon',
    bankAccountNumber: '00360044556677',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Training_Handbook_Invoice.pdf',
    notes: 'Onboarding training handbooks.'
  },
  {
    id: '9',
    claimId: 'EXP-2026-855',
    employee: 'Zaid Qasim',
    employeeId: 'EMP-0190',
    department: 'IT',
    reason: 'Annual Cloud Backup License',
    category: 'IT & Cloud Infrastructure',
    approvedDate: 'Oct 19, 2026',
    approvalChain: '2/3 Approved',
    amount: 400000,
    currency: 'RP',
    bankName: 'Bank Mandiri',
    bankAccountNumber: '1370019284799',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Cloud_Hosting_Invoice.pdf',
    notes: 'Storage backup monthly add-on.'
  },
  {
    id: '10',
    claimId: 'EXP-2026-850',
    employee: 'Omar Farooq',
    employeeId: 'EMP-0160',
    department: 'Operations',
    reason: 'Visa Processing Logistics & Courier',
    category: 'Inter-office Logistics & Courier',
    approvedDate: 'Oct 18, 2026',
    approvalChain: '2/3 Approved',
    amount: 250000,
    currency: 'RP',
    bankName: 'Al Rajhi Bank',
    bankAccountNumber: '49201928371999',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'DHL_Airway_Bill.pdf',
    notes: 'Express visa shipment.'
  },
  {
    id: '11',
    claimId: 'EXP-2026-845',
    employee: 'Karim Mostafa',
    employeeId: 'EMP-0175',
    department: 'Marketing',
    reason: 'Meta Summit Expo Banner Printing',
    category: 'Stationery & Printing',
    approvedDate: 'Oct 17, 2026',
    approvalChain: '2/3 Approved',
    amount: 300000,
    currency: 'RP',
    bankName: 'Bank Central Asia (BCA)',
    bankAccountNumber: '8290192899',
    status: 'Ready for Payment',
    receiptsCount: 2,
    receiptName: 'Banner_Print_Receipt.pdf',
    notes: 'Rollup banners for conference booth.'
  },
  {
    id: '12',
    claimId: 'EXP-2026-840',
    employee: 'Bilal Saeed',
    employeeId: 'EMP-0210',
    department: 'Transportation',
    reason: 'Fleet Highway Toll Subscriptions',
    category: 'Transportation & Fuel',
    approvedDate: 'Oct 16, 2026',
    approvalChain: '2/3 Approved',
    amount: 200000,
    currency: 'RP',
    bankName: 'National Commercial Bank (NCB)',
    bankAccountNumber: '10928374829199',
    status: 'Ready for Payment',
    receiptsCount: 1,
    receiptName: 'Toll_Pass_Receipt.pdf',
    notes: 'Monthly fleet highway RFID tag recharge.'
  }
];
