import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { 
  X, 
  ShieldCheck, 
  Copy, 
  Check, 
  User, 
  Server, 
  Lock, 
  FileText, 
  Download,
  Calendar,
  MapPin,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Shield,
  Layers
} from 'lucide-react';
import type { AuditTrailLogItem } from '../types';

interface AuditStepDetailModalProps {
  logs: AuditTrailLogItem[];
  currentIndex: number;
  claimReference: string;
  onSelectIndex: (index: number) => void;
  onClose: () => void;
}

export const AuditStepDetailModal: React.FC<AuditStepDetailModalProps> = ({
  logs,
  currentIndex,
  claimReference,
  onSelectIndex,
  onClose
}) => {
  const { t } = useTranslation();
  const [copied, setCopied] = useState(false);
  const log = logs[currentIndex] || logs[0];

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      } else if (e.key === 'ArrowLeft' && currentIndex > 0) {
        onSelectIndex(currentIndex - 1);
      } else if (e.key === 'ArrowRight' && currentIndex < logs.length - 1) {
        onSelectIndex(currentIndex + 1);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentIndex, logs.length, onClose, onSelectIndex]);

  if (!log) return null;

  const handleCopyHash = () => {
    navigator.clipboard.writeText(log.signatureHash);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadStepProof = () => {
    const proofText = `===============================================================
       COMPLIANCE & EXECUTION AUDIT PROOF CERTIFICATE
===============================================================
Audit Reference   : ${claimReference}
Step Number       : Step ${log.stepNumber} of ${logs.length}
Step Action       : ${log.title}
Timestamp         : ${log.timestamp}
Audit Status      : COMPLIANCE PASSED & DIGITALLY VERIFIED

--- ACTOR IDENTITY ---
Authorized Actor  : ${log.actor}
Role & Title      : ${log.actorRole}
Department        : ${log.actorDepartment || 'N/A'}
Auth Mechanism    : ${log.authMethod}

--- TELEMETRY & NETWORK ---
Origin IP Address : ${log.ipAddress}
Physical Location : ${log.location}

--- CRYPTOGRAPHIC SIGNATURE ---
Hash Algorithm    : SHA-256 (HMAC-SHA256 Signed)
Digital Signature : ${log.signatureHash}

--- GOVERNANCE CHECKLIST ---
Policy Check      : ${log.policyCheckPassed ? 'PASSED (100% Compliant)' : 'FLAGGED'}
Policy Notes      : ${log.policyCheckDetails || 'Verified under standard corporate rules.'}

--- AUDITOR / GATEWAY REMARKS ---
${log.notes}
===============================================================
Generated by Manazil Al Mukhtara Enterprise Finance Gateway
Audit Trace ID: ${claimReference}-${log.id}
`;

    const blob = new Blob([proofText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Audit_Proof_Step_${log.stepNumber}_${claimReference}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const isFirst = currentIndex === 0;
  const isLast = currentIndex === logs.length - 1;

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0c0d0f]/65 backdrop-blur-sm p-3 sm:p-5 animate-fade-in"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl border border-slate-200/90 shadow-2xl max-w-3xl w-full overflow-hidden animate-scale-up font-sans flex flex-col max-h-[90vh]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Top Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/80 flex-shrink-0">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center font-bold shadow-xs">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <span className="text-[11px] font-extrabold uppercase tracking-wider text-blue-700 bg-blue-100/70 px-2 py-0.5 rounded">
                  {t('preExecutionPayment.stepOf', { current: log.stepNumber, total: logs.length }) || `Step ${log.stepNumber} of ${logs.length}`}
                </span>
                <span className="text-[11px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 flex items-center space-x-1">
                  <CheckCircle2 className="w-3 h-3 inline mr-1 text-emerald-600" />
                  {t('preExecutionPayment.verifiedImmutable') || 'Verified & Immutable'}
                </span>
              </div>
              <h3 className="text-[16px] font-bold text-slate-900 mt-0.5 tracking-tight">
                {log.title}
              </h3>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            {/* Step Pager Controls */}
            <div className="flex items-center bg-white border border-slate-200 rounded-lg p-0.5 shadow-2xs mr-1">
              <button
                type="button"
                onClick={() => !isFirst && onSelectIndex(currentIndex - 1)}
                disabled={isFirst}
                className="p-1 rounded text-slate-500 hover:text-slate-800 disabled:opacity-30 disabled:cursor-not-allowed hover:bg-slate-100 transition-colors cursor-pointer"
                title="Previous Step (Left Arrow)"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-[11.5px] font-bold text-slate-600 px-2 select-none">
                {currentIndex + 1} / {logs.length}
              </span>
              <button
                type="button"
                onClick={() => !isLast && onSelectIndex(currentIndex + 1)}
                disabled={isLast}
                className="p-1 rounded text-slate-500 hover:text-slate-800 disabled:opacity-30 disabled:cursor-not-allowed hover:bg-slate-100 transition-colors cursor-pointer"
                title="Next Step (Right Arrow)"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-slate-200/60 cursor-pointer transition-colors"
              title="Close (Esc)"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Step Tabs Strip */}
        <div className="px-6 py-2 bg-slate-100/60 border-b border-slate-200/70 flex items-center space-x-1.5 overflow-x-auto flex-shrink-0">
          {logs.map((item, idx) => {
            const isActive = idx === currentIndex;
            return (
              <button
                key={item.id}
                type="button"
                onClick={() => onSelectIndex(idx)}
                className={`px-3 py-1 rounded-lg text-[11.5px] font-semibold transition-all whitespace-nowrap cursor-pointer flex items-center space-x-1.5 ${
                  isActive
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-white text-slate-600 hover:bg-slate-200/70 hover:text-slate-900 border border-slate-200/80'
                }`}
              >
                <span className={`w-4 h-4 rounded-full text-[10px] flex items-center justify-center font-bold ${
                  isActive ? 'bg-white text-blue-600' : 'bg-slate-100 text-slate-500'
                }`}>
                  {idx + 1}
                </span>
                <span className="truncate max-w-[130px]">{item.title.split(' ')[0]} {item.title.split(' ')[1] || ''}</span>
              </button>
            );
          })}
        </div>

        {/* Modal Body - 2 Column Clean Grid */}
        <div className="p-6 overflow-y-auto space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Left Column: Signer & Network */}
            <div className="space-y-4">
              {/* Authorized Signer */}
              <div className="p-4 bg-slate-50/80 rounded-xl border border-slate-200/80 space-y-2.5">
                <div className="flex items-center space-x-2 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <User className="w-3.5 h-3.5 text-blue-600" />
                  <span>{t('preExecutionPayment.authorizedSigner') || 'Authorized Signer / Gateway'}</span>
                </div>
                <div className="flex items-start space-x-3 pt-0.5">
                  <div className="w-9 h-9 rounded-full bg-blue-100 text-blue-700 font-extrabold flex items-center justify-center text-[13px] flex-shrink-0 border border-blue-200">
                    {log.actor.slice(0, 2).toUpperCase()}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-[13.5px] font-bold text-slate-900 truncate">{log.actor}</p>
                    <p className="text-[12px] text-slate-600 font-medium">{log.actorRole}</p>
                    {log.actorDepartment && (
                      <p className="text-[11px] text-slate-400 mt-0.5">{log.actorDepartment}</p>
                    )}
                  </div>
                </div>
              </div>

              {/* Authentication Proof */}
              <div className="p-4 bg-slate-50/80 rounded-xl border border-slate-200/80 space-y-2">
                <div className="flex items-center space-x-2 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <Lock className="w-3.5 h-3.5 text-emerald-600" />
                  <span>{t('preExecutionPayment.authProof') || 'Authentication Proof'}</span>
                </div>
                <div>
                  <p className="text-[13px] font-semibold text-slate-800">{log.authMethod}</p>
                  <div className="flex items-center space-x-2 mt-1.5">
                    <span className="text-[10.5px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                      Dual-Factor Validated
                    </span>
                    <span className="text-[10.5px] font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
                      SAMA Compliant
                    </span>
                  </div>
                </div>
              </div>

              {/* Telemetry & Network */}
              <div className="p-4 bg-slate-50/80 rounded-xl border border-slate-200/80 space-y-2.5 text-[12.5px]">
                <div className="flex items-center space-x-2 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <Server className="w-3.5 h-3.5 text-slate-600" />
                  <span>{t('preExecutionPayment.telemetry') || 'Audit Telemetry & Network Trail'}</span>
                </div>
                <div className="space-y-1.5 text-[12px]">
                  <div className="flex items-center space-x-2 text-slate-600">
                    <Calendar className="w-3.5 h-3.5 text-slate-400 flex-shrink-0" />
                    <span><strong className="text-slate-700">Timestamp:</strong> {log.timestamp}</span>
                  </div>
                  <div className="flex items-center space-x-2 text-slate-600">
                    <MapPin className="w-3.5 h-3.5 text-slate-400 flex-shrink-0" />
                    <span><strong className="text-slate-700">Origin:</strong> {log.location}</span>
                  </div>
                  <div className="text-[11px] text-slate-600 font-mono bg-white p-2 rounded-lg border border-slate-200/80 truncate">
                    IP: {log.ipAddress}
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column: Cryptographic Signature & Governance */}
            <div className="space-y-4">
              {/* SHA-256 Signature Card */}
              <div className="p-4 bg-blue-50/40 rounded-xl border border-blue-100 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-1.5 text-[11px] font-bold text-blue-800 uppercase tracking-wider">
                    <Shield className="w-3.5 h-3.5 text-blue-600" />
                    <span>{t('preExecutionPayment.digitalSignature') || 'Digital SHA-256 Audit Signature'}</span>
                  </div>
                  <button
                    type="button"
                    onClick={handleCopyHash}
                    className="flex items-center space-x-1 text-[11px] font-bold text-blue-600 hover:text-blue-700 bg-white px-2 py-1 rounded-md border border-blue-200 shadow-2xs cursor-pointer transition-all hover:shadow-xs"
                  >
                    {copied ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                    <span>{copied ? (t('preExecutionPayment.hashCopied') || 'Copied!') : (t('preExecutionPayment.copyHash') || 'Copy Hash')}</span>
                  </button>
                </div>
                <div className="p-2.5 bg-white rounded-lg border border-blue-200/80 font-mono text-[10.5px] text-blue-900 break-all select-all leading-relaxed">
                  {log.signatureHash}
                </div>
              </div>

              {/* Governance & Policy */}
              {log.policyCheckDetails && (
                <div className="p-4 bg-emerald-50/40 rounded-xl border border-emerald-100 space-y-1 text-[12px]">
                  <div className="flex items-center space-x-1.5 text-[11px] font-bold text-emerald-800 uppercase tracking-wider">
                    <Layers className="w-3.5 h-3.5 text-emerald-600" />
                    <span>{t('preExecutionPayment.governancePolicy') || 'Governance & Policy Compliance'}</span>
                  </div>
                  <p className="text-emerald-950 font-medium leading-relaxed pt-0.5">
                    {log.policyCheckDetails}
                  </p>
                </div>
              )}

              {/* Signer Remarks & Notes */}
              <div className="p-4 bg-slate-50/80 rounded-xl border border-slate-200/80 space-y-1.5 text-[12.5px]">
                <div className="flex items-center space-x-1.5 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <FileText className="w-3.5 h-3.5 text-slate-600" />
                  <span>{t('preExecutionPayment.signerRemarks') || 'Signer & Execution Remarks'}</span>
                </div>
                <p className="text-slate-700 italic text-[12px] bg-white p-2.5 rounded-lg border border-slate-200/80 leading-relaxed">
                  &ldquo;{log.notes}&rdquo;
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 bg-slate-50/90 border-t border-slate-100 flex items-center justify-between flex-shrink-0">
          <button
            type="button"
            onClick={handleDownloadStepProof}
            className="px-3.5 py-2 bg-white hover:bg-slate-100 border border-slate-200 text-slate-700 font-semibold rounded-xl text-[12px] transition-all cursor-pointer flex items-center space-x-1.5 shadow-2xs"
          >
            <Download className="w-3.5 h-3.5 text-slate-500" />
            <span>Export Step Certificate (.txt)</span>
          </button>

          <div className="flex items-center space-x-2">
            {!isFirst && (
              <button
                type="button"
                onClick={() => onSelectIndex(currentIndex - 1)}
                className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-xl text-[12px] transition-all cursor-pointer flex items-center space-x-1"
              >
                <ChevronLeft className="w-3.5 h-3.5" />
                <span>{t('preExecutionPayment.prevStep') || 'Prev'}</span>
              </button>
            )}

            {!isLast ? (
              <button
                type="button"
                onClick={() => onSelectIndex(currentIndex + 1)}
                className="px-3.5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-[12px] transition-all cursor-pointer flex items-center space-x-1 shadow-xs"
              >
                <span>{t('preExecutionPayment.nextStep') || 'Next Step'}</span>
                <ChevronRight className="w-3.5 h-3.5" />
              </button>
            ) : (
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-xl text-[12px] transition-all cursor-pointer shadow-xs"
              >
                {t('preExecutionPayment.closeInspector') || 'Close Inspector'}
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

