import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { 
  ShieldCheck, 
  Download, 
  Copy, 
  Check, 
  ChevronRight, 
  ExternalLink,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import type { AuditTrailLogItem } from '../types';
import { AuditStepDetailModal } from './AuditStepDetailModal';

interface ComplianceAuditTrailCardProps {
  logs: AuditTrailLogItem[];
  claimReference?: string;
}

export const ComplianceAuditTrailCard: React.FC<ComplianceAuditTrailCardProps> = ({ 
  logs,
  claimReference = 'PRJ-RYD-2024'
}) => {
  const { t } = useTranslation();
  const [selectedLogIndex, setSelectedLogIndex] = useState<number | null>(null);
  const [copiedMaster, setCopiedMaster] = useState(false);
  const [expandAll, setExpandAll] = useState(false);

  const handleCopyMasterHash = () => {
    const masterSignature = `AUDIT-MASTER-${claimReference}-${Date.now()}-SHA256:7f99a12c884ef0192834019283401928340bcfe0192834019283401928340192834`;
    navigator.clipboard.writeText(masterSignature);
    setCopiedMaster(true);
    setTimeout(() => setCopiedMaster(false), 2000);
  };

  const handleDownloadFullCertificate = () => {
    let report = `======================================================================
         OFFICIAL COMPLIANCE & REIMBURSEMENT AUDIT TRAIL
             MANAZIL AL MUKHTARA GROUP - FINANCE SYSTEM
======================================================================
Claim Reference       : ${claimReference}
Audit Report Date     : ${new Date().toLocaleString()}
Overall Policy Status : 100% COMPLIANT (SAMA / ZATCA / ISO 27001 AUDITED)
Master Verification   : VERIFIED & IMMUTABLE LEDGER RECORD
======================================================================

CHRONOLOGICAL AUDIT TIMELINE:
`;

    logs.forEach((log, index) => {
      report += `
----------------------------------------------------------------------
STEP ${index + 1}: ${log.title.toUpperCase()}
----------------------------------------------------------------------
Timestamp       : ${log.timestamp}
Detail          : ${log.detail}
Authorized Sign : ${log.actor || 'System'} (${log.actorRole || 'System Gateway'})
Department      : ${log.actorDepartment || 'Operations'}
Auth Method     : ${log.authMethod || 'Standard'}
Network IP / Geo: ${log.ipAddress || 'Internal'} | ${log.location || 'Riyadh'}
SHA-256 Hash    : ${log.signatureHash || 'N/A'}
Policy Check    : ${log.policyCheckPassed ? 'PASSED [OK]' : 'PENDING'}
Signer Remarks  : "${log.notes || 'No additional remarks.'}"
`;
    });

    report += `
======================================================================
                       END OF AUDIT CERTIFICATE
      Cryptographically generated by Manazil Al Mukhtara Treasury
======================================================================`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Audit_Compliance_Trail_${claimReference}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="bg-white rounded-2xl border border-slate-200/90 shadow-xs p-7 space-y-6">
        {/* Header with Title and Functional Actions */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-2 border-b border-slate-100">
          <div className="space-y-0.5">
            <div className="flex items-center space-x-2">
              <h3 className="text-[16px] font-bold text-slate-900 tracking-tight">
                {t('preExecutionPayment.auditTrail') || 'Compliance & Execution Audit Trail'}
              </h3>
              <span className="inline-flex items-center space-x-1 px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
                <ShieldCheck className="w-3 h-3" />
                <span>{t('preExecutionPayment.verifiedImmutable') || 'Audited'}</span>
              </span>
            </div>
            <p className="text-[11.5px] text-slate-400 font-medium">
              Click any audit step to inspect cryptographic verification proofs
            </p>
          </div>

          <div className="flex items-center space-x-2 flex-shrink-0">
            <button
              type="button"
              onClick={handleCopyMasterHash}
              className="px-2.5 py-1.5 bg-slate-50 hover:bg-slate-100 text-slate-600 rounded-lg text-[11px] font-semibold border border-slate-200 transition-colors cursor-pointer flex items-center space-x-1"
              title="Copy Master Audit Hash"
            >
              {copiedMaster ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3 text-slate-400" />}
              <span>{copiedMaster ? (t('preExecutionPayment.hashCopied') || 'Hash Copied!') : (t('preExecutionPayment.copyHash') || 'Copy Hash')}</span>
            </button>

            <button
              type="button"
              onClick={handleDownloadFullCertificate}
              className="px-2.5 py-1.5 bg-slate-50 hover:bg-slate-100 text-slate-600 rounded-lg text-[11px] font-semibold border border-slate-200 transition-colors cursor-pointer flex items-center space-x-1"
              title="Download Full Audit Certificate"
            >
              <Download className="w-3 h-3 text-slate-400" />
              <span>{t('common.download') || 'Export'}</span>
            </button>

            <button
              type="button"
              onClick={() => setExpandAll(!expandAll)}
              className="p-1.5 bg-slate-50 hover:bg-slate-100 text-slate-500 rounded-lg border border-slate-200 transition-colors cursor-pointer"
              title={expandAll ? 'Collapse details' : 'Expand all details'}
            >
              {expandAll ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
            </button>
          </div>
        </div>

        {/* Audit Trail Timeline */}
        <div className="relative pl-6 space-y-6">
          {/* Continuous Vertical Guide Line */}
          <div className="absolute left-[6.5px] top-2 bottom-2 w-[1.5px] bg-slate-100 -translate-x-1/2" />

          {logs.map((log, index) => {
            return (
              <div 
                key={log.id} 
                onClick={() => setSelectedLogIndex(index)}
                className="group relative -ml-2 pl-6 pr-3 py-1.5 rounded-xl hover:bg-slate-50/80 transition-all cursor-pointer select-none"
              >
                {/* Timeline Dot Marker */}
                <div className="absolute left-[2.5px] top-2.5 -translate-x-1/2 z-10 flex items-center justify-center">
                  {log.dotColor === 'gray' && (
                    <div className="w-3 h-3 rounded-full bg-slate-400 shadow-2xs" />
                  )}

                  {log.dotColor === 'green' && (
                    <div className="w-3 h-3 rounded-full border-2 border-emerald-500 bg-white" />
                  )}

                  {log.dotColor === 'blue' && (
                    <div className="w-3 h-3 rounded-full border-2 border-blue-600 bg-white ring-4 ring-blue-100/90 animate-pulse" />
                  )}
                </div>

                {/* Main Step Content */}
                <div className="flex items-start justify-between">
                  <div className="space-y-0.5">
                    <div className="font-bold text-slate-800 text-[13px] group-hover:text-blue-600 transition-colors flex items-center space-x-1.5">
                      <span>{log.title}</span>
                      <ExternalLink className="w-3 h-3 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity" />
                    </div>

                    <div className="text-[11.5px] text-slate-400 font-medium">
                      {log.timestamp} • {log.detail}
                    </div>

                    {/* Inline Expanded Preview if toggled */}
                    {expandAll && (
                      <div className="mt-2 p-2.5 bg-slate-100/60 rounded-lg text-[11px] text-slate-600 space-y-1 animate-fade-in border border-slate-200/50">
                        <div className="flex items-center justify-between">
                          <span className="font-semibold text-slate-700">Signer: {log.actor}</span>
                          <span className="text-emerald-700 font-bold bg-emerald-50 px-1.5 py-0.5 rounded text-[10px]">
                            {log.authMethod}
                          </span>
                        </div>
                        <p className="text-slate-500 italic">&ldquo;{log.notes}&rdquo;</p>
                      </div>
                    )}
                  </div>

                  {/* Right Action Hint */}
                  <div className="opacity-0 group-hover:opacity-100 transition-opacity pl-2 self-center">
                    <span className="text-[10.5px] font-bold text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-100 flex items-center space-x-0.5">
                      <span>{t('preExecutionPayment.inspect') || 'Inspect'}</span>
                      <ChevronRight className="w-3 h-3" />
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Bottom Banner */}
        <div className="p-3 bg-slate-50/70 rounded-xl border border-slate-100 flex items-center justify-between text-[11px] text-slate-500">
          <div className="flex items-center space-x-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />
            <span className="font-medium text-slate-600">All 6 lifecycle checkpoints cryptographically validated</span>
          </div>
          <button
            type="button"
            onClick={handleDownloadFullCertificate}
            className="text-blue-600 font-bold hover:underline cursor-pointer flex items-center space-x-1"
          >
            <span>{t('preExecutionPayment.exportCertificate') || 'Download Audit Log (.txt)'}</span>
          </button>
        </div>
      </div>

      {/* Step Detail Inspection Modal */}
      {selectedLogIndex !== null && (
        <AuditStepDetailModal
          logs={logs}
          currentIndex={selectedLogIndex}
          claimReference={claimReference}
          onSelectIndex={(index) => setSelectedLogIndex(index)}
          onClose={() => setSelectedLogIndex(null)}
        />
      )}
    </>
  );
};

